name: CI Pipeline
# This workflow will build, test, and push the Docker image to Docker Hub
# when there is a push to the main branch or manually triggered
# It will also run the tests and build the package
# and upload the artifacts for the trained model and the built package
# The workflow is divided into four jobs: train, test, build, and push-image
# The train job will train the model and save it as a pickle file
# The test job will run the tests using pytest
# The build job will build the package using setuptools
# The push-image job will build the Docker image and push it to Docker Hub
# The workflow will run on the latest version of Ubuntu
# The workflow will run on the latest version of Python 3.12.3
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.3'
    - name: Install dependencies
      run: pip install -r requirements/requirements.txt
    - name: Train and save pipeline
      run: python bikeshare_model/train_pipeline.py
    - uses: actions/upload-artifact@v4
      with:
        name: my-trained-pipeline
        path: bikeshare_model/trained_models/*.pkl
        retention-days: 1

  test:
    needs: train
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.3'
    - uses: actions/download-artifact@v4
      with:
        name: my-trained-pipeline
        path: bikeshare_model/trained_models
    - name: Install dependencies
      run: pip install -r requirements/requirements.txt
    - name: Test with pytest
      run: pytest

  build:
    needs: [train, test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.3'
    - uses: actions/download-artifact@v4
      with:
        name: my-trained-pipeline
        path: bikeshare_model/trained_models
    - name: Install dependencies
      run: pip install --upgrade build
    - name: Build package
      run: python -m build
    - uses: actions/upload-artifact@v4
      with:
        name: my-build-package
        path: dist/*.whl
        retention-days: 1

  push-image:
    needs: [train, test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v3

    - uses: actions/download-artifact@v4
      with:
        name: my-build-package
        path: bike_sharing_api

    - name: Login to Docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build the Docker image for Fastapi app
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: docker build . -f Dockerfile -t $DOCKER_USER/bikeshare-api:latest

    - name: Push the Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: docker push $DOCKER_USER/bikeshare-api

    - name: Logout to Docker hub
      run: docker logout

